/*
    Copyright 2021 Tom Papke

   Licensed under the Apache License, Version 2.0 (the "License"),
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

export const EvalConfig = {

  RUN_AUTOGENERATED_TESTS: true,

  PROGRESSION: {
    EXPONENTIAL: true,
    INTERVAL: 10,
    FACTOR: 2,
    LIMIT: 10,
    INITIAL_SIZE: 100,
    REPS: 1,

    INITIAL_CHANGES: 5,
  },

  //TODO option to store genearted models in test case folder
  // option to turn off generation use old models

  //TODO filename objec t

  FILENAMES: {
    GEN_PARAMS: 'genParams.json',
    CHANGE_PARAMS: 'changeParams.json',
    RUN_SCRIPT: 'run.sh',
    OLD_TREE: 'old.xml',
    NEW_TREE: 'new.xml',
    EXPECTED_DIFF: 'info.json',
    EXPECTED_MATCHES: 'expected.json',
    BASE: 'base.xml',
    BRANCH_1: '1.xml',
    BRANCH_2: '2.xml',
    EXPECTED_MERGE_PREFIX: 'expected',
    ACCEPTED_MERGE_PREFIX: 'accepted',
  },

  MATCH_CASES_DIR: 'test/test_set/match_cases',
  DIFF_CASES_DIR: 'test/test_set/diff_cases',
  MERGE_CASES_DIR: 'test/test_set/merge_cases',

  EXECUTION_OPTIONS: {
    timeout: 30000, //30s
    maxBuffer: 100 * 1024 * 1024 //100 MiB
  },

  MATCHINGS: {
    CPEEMATCH: {
      displayName: 'CpeeMatch',
      path: '',
    },
  },
  DIFFS: {
    CPEEDIFF: {
      displayName: 'CpeeDiff',
      path: ''
    },
    XMLDIFF: {
      displayName: 'xmldiff',
      path: '../xml_diff_algos/xmldiff',
    },
    DIFFXML: {
      displayName: 'DiffXml',
      path: '../xml_diff_algos/diffxml',
    },
    DELTAJS: {
      displayName: 'Delta.js',
      path: '../xml_diff_algos/deltajs',
    },
    XCC: {
      displayName: 'XCC',
      path: '../xml_diff_algos/xcc',
    },
    XYDIFF: {
      displayName: 'XyDiff',
      path: '../xml_diff_algos/xydiff',
    },
    JNDIFF: {
      displayName: 'JNDiff',
      path: '../xml_diff_algos/jndiff',
    }
  },

  MERGES: {
    CPEEMERGE: {
      displayName: 'CpeeMerge',
      path: ''
    },
    _3DM: {
      displayName: '3DM',
      path: '../xml_merge_algos/3dm'
    },
    XCC: {
      displayName: 'XCC Diff & Patch',
      path: '../xml_merge_algos/xcc'
    }
  },

  //TODO criteria matching
  //     #tests passed (accuracy and overall quality)
  //      runtime
  //      edit script size
  //      #nodes matched
  //      merging #tests with expected result

};

