/**
 * Configuration object for the automated evaluation framework.
 * @type {Object}
 */
export const EvalConfig = {

  RUN_AUTOGENERATED_TESTS: true,
  OUTPUT_LATEX: false,

  REPS: 5,
  SIZE_GROWTH: {
    INTERVAL: 100,
    LIMIT: 20,
  },
  CHANGE_GROWTH: {
    INTERVAL: 5,
    LIMIT: 20,
  },

  FILENAMES: {
    GEN_PARAMS: 'genParams.json',
    CHANGE_PARAMS: 'changeParams.json',
    RUN_SCRIPT: 'run.sh',
    OLD_TREE: 'old.xml',
    NEW_TREE: 'new.xml',
    EXPECTED_DIFF: 'info.json',
    EXPECTED_MATCHES: 'expected.json',
    BASE: 'base.xml',
    BRANCH_1: '1.xml',
    BRANCH_2: '2.xml',
    EXPECTED_MERGE_PREFIX: 'expected',
    ACCEPTED_MERGE_PREFIX: 'accepted',
  },

  EXECUTION_OPTIONS: {
    timeout: 30000, // 30s
    maxBuffer: 100 * 1024 * 1024, // 100 MiB
  },

  MATCHINGS: {
    CPEEMATCH: {
      displayName: 'CpeeMatch',
      path: '',
    },
  },

  // All paths are relative to the project root directory

  MATCH_CASES_DIR: 'test_set/match_cases',
  DIFF_CASES_DIR: 'test_set/diff_cases',
  MERGE_CASES_DIR: 'test_set/merge_cases',

  DIFFS: {
    CPEEDIFF: {
      displayName: 'CpeeDiff',
      path: './src/main.js',
    },
    XMLDIFF: {
      displayName: 'xmldiff',
      path: '../xml_diff_algos/xmldiff',
    },
    DIFFXML: {
      displayName: 'DiffXml',
      path: '../xml_diff_algos/diffxml',
    },
    DELTAJS: {
      displayName: 'Delta.js',
      path: '../xml_diff_algos/deltajs',
    },
    XCC: {
      displayName: 'XCC',
      path: '../xml_diff_algos/xcc',
    },
    XYDIFF: {
      displayName: 'XyDiff',
      path: '../xml_diff_algos/xydiff',
    },
    JNDIFF: {
      displayName: 'JNDiff',
      path: '../xml_diff_algos/jndiff',
    },
  },

  MERGES: {
    CPEEMERGE: {
      displayName: 'CpeeMerge',
      path: './src/main.js',
    },
    _3DM: {
      displayName: '3DM',
      path: '../xml_merge_algos/3dm',
    },
    XCC: {
      displayName: 'XCC Diff & Patch',
      path: '../xml_merge_algos/xcc',
    },
  },
};

